server:
  port: 8082

spring:
  application:
    name: codewisdom-code-analysis
  profiles:
    active: local
  cloud:
    nacos:
      discovery:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-}] %logger{36} - %msg%n"
