server:
  port: 8084

spring:
  application:
    name: codewisdom-evaluation-export
  profiles:
    active: local
  cloud:
    nacos:
      discovery:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-}] %logger{36} - %msg%n"
